const ShopSchema = {
  name: "Shop",
  primaryKey: "id",
  properties: {
    id: "int",
    name: "string?",
    shopName: "string?",
    email: "string?",
    phone: "string?",
    allowedDevices: "int?",
    features: "string?",
    companyId: "int?",
    addressId: "int?",
    taxId: "int?",
    createdAt: "string?",
    updatedAt: "string?",
    deletedAt: "string?",
    licenseKey: "string?",
    licenseRegAt: "string?",
    licenseExpiresAt: "string?",
    otp: "string?",
    otpCreatedAt: "string?",
    otpExpireAt: "string?",
    shopLogoUrl: "string?",
  },
};

// const CompanySchema = {
//   name: "Company",
//   primaryKey: "id",
//   properties: {
//     id: "int",
//     email: "string?",
//     companyName: "string?",
//     companyLogoUrl: "string?",
//     phone: "string?",
//     maxLicense: "int?",
//     addressId: "int?",
//     taxId: "int?",
//     createdAt: "string?",
//     updatedAt: "string?",
//     deletedAt: "string?",
//   },
// };

// const AddressSchema = {
//   name: "Address",
//   primaryKey: "id",
//   properties: {
//     id: "int",
//     isPrimary: "int?",
//     label: "string?",
//     phone: "string?",
//     addressLine1: "string?",
//     addressLine2: "string?",
//     city: "string?",
//     state: "string?",
//     country: "string?",
//     pincode: "string?",
//     locationLat: "string?",
//     locationLong: "string?",
//     createdAt: "string?",
//     updatedAt: "string?",
//     deletedAt: "string?",
//   },
// };

const CartSchema = {
  name: "Cart",
  primaryKey: "id",
  properties: {
    centerStoneCertificate: "string?",
    centerStoneColor: "string?",
    centerStoneCut: "string?",
    centerStoneQuality: "string?",
    centerStoneShape: "string?",
    centerStoneSize: "string?",
    centerStoneType: "string?",
    centerStoneWeight: "string?",
    collectionLine: "string?",
    company: "string?",
    costPrice: "string?",
    counterDescription: "string?",
    counterNumber: "string?",
    customer: "string?",
    deletedAt: "string?",
    designNumber: "string?",
    diamondPrice: "string?",
    findingMetal: "string?",
    findingMetalPurity: "string?",
    findingType: "string?",
    findingWeight: "string?",
    fobPrice: "string?",
    goldLock: "string?",
    grossWeight: "string?",
    id: "int",
    imageName: "string?",
    imageUrl: "string?",
    itemCategory: "string?",
    itemStatus: "string?",
    itemType: "string?",
    kundanPcs: "string?",
    kundanWeight: "string?",
    laborChargesPerGram: "string?",
    laborPrice: "string?",
    location: "string?",
    meenaWeight: "string?",
    metalPrice: "string?",
    metalPurity: "string?",
    metalType: "string?",
    metalWeight: "string?",
    netWeight: "string?",
    newlyImported: "string?",
    orderProductQuantity: { type: "int?", default: 1 },
    orderProductRemarks: { type: "string?", default: "" },
    owner: "string?",
    platinumLock: "string?",
    quantity: "string?",
    remarks: "string?",
    reserved1: "string?",
    reserved2: "string?",
    reserved3: "string?",
    reserved4: "string?",
    reserved5: "string?",
    reserved6: "string?",
    reserved7: "string?",
    rfidTag: "string?",
    salesManName: "string?",
    selected: "string?",
    sellingPrice: "string?",
    setId: "string?",
    setImageName: "string?",
    silverLock: "string?",
    size: "string?",
    skuNumber: "string?",
    stoneCertificate: "string?",
    stoneColor: "string?",
    stoneCount: "string?",
    stoneCut: "string?",
    stonePrice: "string?",
    stoneQuality: "string?",
    stoneShape: "string?",
    stoneSize: "string?",
    stoneType: "string?",
    stoneWeight: "string?",
    synced: "string?",
    totalDiamondWeight: "string?",
    totalStoneCount: "string?",
    totalStoneWeight: "string?",
    trayDescription: "string?",
    trayNumber: "string?",
  },
};

export { ShopSchema, CartSchema };
